services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
    environment:
      FASTAPI_ENV: ${FASTAPI_ENV:-DEV}
      WEB_CONCURRENCY: ${WEB_CONCURRENCY:-2}
    ports:
      - "${PORT:-5000}:5000"
