version: 1
disable_existing_loggers: False
formatters:
  default:
    (): app.logging.JsonFormatter
    format: {
            "levelname": "levelname",
            "message": "message",
            "message": "message",
            "timestamp": "asctime",
            "request_id": "request_id",
        }
  access:
    (): app.logging.JsonFormatter
    format: {
            "levelname": "levelname",
            "message": "message",
            "message": "message",
            "timestamp": "asctime",
            "request_id": "request_id",
        }
filters:
  injection_filter:
    (): app.logging.RequestIdFilter
handlers:
  default:
    formatter: default
    class: logging.StreamHandler
    stream: ext://sys.stderr
    filters: [injection_filter]
  access:
    formatter: access
    class: logging.StreamHandler
    stream: ext://sys.stdout
    filters: [injection_filter]
loggers:
  uvicorn.error:
    level: INFO
    handlers:
      - default
    propagate: no
  uvicorn.access:
    level: INFO
    handlers:
      - access
    propagate: no
